### ISSUE TITLE
meta rebase: conflict in .gitmodules

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#141]
See the attached shell script for a repro :

[test-rebase.zip](https://github.com/twosigma/git-meta/files/634429/test-rebase.zip)

**Comment by novalis** [comment]
FWIW, I can repro this with a plain git rebase (that is, s/meta // in the last line of that shell script).

**Comment by novalis** [comment]
OK, so at least on plain git, this won't require core changes (haven't checked libgit2).  We can add a .gitattributes file with the following text:
.gitmodules merge=merge-gitmodules

Then we need to define merge-gitmodules in our git config.  Of course, actually writing it will be a little tricky, because it's a quasi-ordered set.  https://github.com/mirkokiefer/diff-merge-patch#ordered-sets might help -- it's the only thing I've found on Google that even remotely solves the problem.

**Comment by novalis** [comment]
In our usage, it is sorted (and thus we can use the much simpler "sets" API).  But in the more-general case, it is not ordered.  So we should decide if we want to support that case.

**Comment by bpeabody** [comment]
FWIW, you can recreate this scenario using the shorthand like:
```bash
$ write-repos -o 'q=B|r=B|x=S:C2-1 q=Sq:1;C3-1 r=Sr:1;Bmaster=2;Bfoo=3'
$ cd x
$ git meta rebase foo
```

**Comment by bpeabody** [comment]
Hmm, is this only a problem when two commits are being merged that were the *first* to add submodules?

**Comment by bpeabody** [comment]
No, the same problem exists, with `q=B|r=B|s=B|x=S:C2-1 s=Ss:1;C3-2 q=Sq:1;C4-2 r=Sr:1;Bmaster=3;Bfoo=4`.

I think it's probably not too hard for git-meta to attempt a merge on the `.gitmodules` file.

**Comment by bpeabody** [comment]
I think it's pretty straightforward to resolve this situation. If I detect a conflict in the `.gitmodules` file, I will:

1. Use `SubmoduleConfigUtil.getSubmodulesFromCommit` to read the modules information from both commits and the merge base -- this method returns a dictionary from submodule name to url.
2. Attempt to create a new dictionary that combines changes from both sides.
3. If I detect that there is a difference between the two sides that is irreconcilable -- they both attempt to add/remove/change the same submodule in different ways -- I will leave it in conflicted state.
4. Otherwise, we write out the adjusted `.gitmodules` file in the rebased commit.

**Comment by novalis** [comment]
Yes, this seems right.  I just wonder if we should write it in C so it's (a) faster and (b) easier to upstream.

**Comment by novalis** [comment]
(I asked the mailing list, and Junio basically said, "Try it.  If it works, we'll probably take it.")

**Comment by bpeabody** [comment]
Great. I'm done writing it in JS, just working on test cases. This can get us over the hump for now, agree that we should upstream it in C.

**Comment by bpeabody** [comment]
Handing this over to @novalis if he wants to upstream a fix to `git` and/or `libgit2`; it's addressed in `git meta` now.
