### ISSUE TITLE
`rebase` is opening submodules unnecessarily

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#144]
I cannot recreate this yet. For example, the following setup creates divergent branches, `master` and `foo`, where foo has a change to the submodule `t`:

```bash
$ write-repos -o 'a=B|b=B:Cj-1;Ck-1;Bmaster=j;Bfoo=k|x=S:C2-1 s=Sa:1,t=Sb:1;C3-2;C4-2 t=Sb:k;Bmaster=3;Bfoo=4;Bold=3
$ cd x
$ git meta rebase foo
```

The rebase does not attempt to open this submodule. Similarly, if you rebase `foo` onto `master`, the submodule is not opened.

**Comment by novalis** [comment]
So, looking at our internal testcase, it appears that there is significant merging going on (the rebase should have used the --onto and base options, but didn't).  And in fact, when we try an ordinary git rebase we see a conflict in the same place.  One might thing that the solution is to use the -p argument to rebase, which attempts to preserve merges.  But in fact, when I try that, it fails too (before it gets to the point where we would expect it to fail).  I don't know why that is -- maybe it's submodule-specific, or maybe it's because our history is too complicated.

**Comment by bpeabody** [comment]
I think I got this fixed.
