### ISSUE TITLE
explain how to create a meta repo

### ISSUE THREAD

**Issue by NicolasRouquette** [twosigma/git-meta#202]
It's unclear how to use git meta to create a meta repo from scratch and add sub-repos to it.

**Comment by bpeabody** [comment]
Until very recently, that was a story that was not well-written. Partly because we're not creating new meta-repos here, and we not adding new sub-repos with `git-meta` (long story there). Also, you would be using mostly vanilla commands to do these operations; they'd look something like:

1. Meta-repos are created just like normal repos, e.g., with `git init`.
1. To create a new sub-repo, you must first create one using whatever technique is provided by your hosting solution, then use `git meta include <url> <path>` to add it to the meta-repo. `git meta include` is a very thin wrapper around `git submodule add`.

With our [omega repo](https://github.com/twosigma/git-meta/wiki/The-Omega-Repo) proposal, things are much different. You can create a meta-repo and add/remove/etc. sub-repos without talking to a back end at all; they really become first-class Git citizens.

I'll extend the user guide to resolve this issue.
