### ISSUE TITLE
`pull` should derive default upstream and branch from tracking info of the current branch.

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#220]
If both remotes are present. This could be more friendly than the current version.
```
$ git meta pull --rebase
Command failed: git -C '/srv/local/1/home/abliss/src/meta2/.git/' fetch -q 'origin'
fatal: Couldn't find remote ref HEAD
 `git -C '/srv/local/1/home/abliss/src/meta2/.git/' fetch -q 'origin'` (exited with error code 128)
$ git meta pull --rebase upstream
usage: git-meta pull [-h] [-r REPOSITORY] [-s SOURCE] [--rebase]
git-meta pull: error: Unrecognized arguments: upstream.
```

**Comment by bpeabody** [comment]
Yeah, there are a couple of things here. We need to change pull to use the normal git syntax instead of `-r` and `-s`. I don't think I'd want to change the default to `upstream` in the GitHub repo; that's just too counter-intuitive to Git which always uses `origin`. I think it would be worth considering if this were part of the long-term strategy for git-meta, but it would likely be a short-term solution even for us.

What I think would be reasonable is allowing the default to be set in configuration, especially since there are other commands (e.g,. `checkout`) that don't normally allow an upstream to be specified in Git that need on in git-meta.

**Comment by bpeabody** [comment]
Added https://github.com/twosigma/git-meta/issues/221 for the syntax change

**Comment by bpeabody** [comment]
Added https://github.com/twosigma/git-meta/issues/222 to allow configuration of default remote.

**Comment by jhedwardyang** [comment]
Could we take advantage of `remote.origin.pushurl` or `git config remote.pushDefault` somehow?

**Comment by gpalumbo** [comment]
Shouldn't pull respect the tracking info on the branch itself?  That would be more natural and make more sense when switching branches at the meta level.
