### ISSUE TITLE
Make `git meta close` more foolproof

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#29]
1) before closing, check for commits which have not been pushed anywhere
2) Instead of running rm -rf .git/modules/foo/bar, maybe make a backup somewhere?

**Comment by bpeabody** [comment]
I don't think we should do (2). This behavior would be un-gitlike. I would say it should:

1. Warn and refuse to run if there are unpunished (or index or working directory) changes.
2. Do `rm -rf` and do not warn if the users passes the `-f` flag.

**Comment by abliss** [comment]
I appreciate the Git mentality of giving the user powerful and dangerous
tools. But git also makes it a priority never to destroy committed data.
Even if you amend or rebase, the reflog is there to save you (at least
until the next gc). Can you name any git operation (even with -f) that
would immediately and permanently destroy a commit?

There doesn't seem to be any reliable way to know that all commits in a
repo exist on the remote. (Even if there were, relying on it isn't very
gitlike either, since the remote itself could become unreachable.)

If you're worried about runaway backups, maybe there's a way to plug into
git gc to do cleanup?

**Comment by bpeabody** [comment]
What I mean by "un-gitlike" is:
1. Many other Git commands can remove user content, they all require some form of `-f` before they delete data.
2. Git users generally are less concerned about such loss because they commit and push often; the idea to back up uncommitted/pushed content because there might be a lot of it makes seems more like an `svn` (or even old-school `hg`) style concept.
3. Specifically, the related `git` command, `git submodule deinit` does `rm -rf` when forced.

I think the idea of making backups is also contrary to the mandate of `git-meta`, which is to do only things that could be done by basic `git` commands; I think we'd have a hard time getting this functionality accepted into Git.

I think giving them a big warning -- clearly show them what is going one -- and not making any destructive changes unless they type `--force` is more than sufficient; the user can easily back up the files on his or her own after seeing the warning.

I'm OK with the possibility of the remote being unreachable or the user doing something clearly wrong to make `remote/origin` branches appear as if the remote has been updated when it actually hasn't.

We will actually be doing a better job than `git submodule deinit`, by the way, which does not check for unpushed commits.

**Comment by bpeabody** [comment]
I think we're good on this now. `close` will not remove workdir contents without `-f`, and and committed/staged changes will be preserved in `.git/modules/<submodule path>` no matter what the user does.
