### ISSUE TITLE
git-meta wrongly uses config to determine which submodules are open

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#64]
Instead, it should use config to determine which submodules *might* be open, and then stat $submodule/.git to determine if the submodule is open.

This is more robust, because (a) it works with git worktrees and (b) it handles the case where you switch to a branch in which a given submodule does not exist.

**Comment by bpeabody** [comment]
I ran into the same problem when working on `rebase` and implemented exactly the solution you recommend for `listOpenSubmodules`; this problem is fixed on `master`.

There is also an `isVisible` method, that should be renamed to be consistent to `isOpen`, that *just* stats `.git`, the rationale being that when you're just looking at a single sub-repo, it's probably more performant to skip to the more definitive check and avoid a linear search through the config file.
